config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/resource-catalogue-ui:
      branch: post-v6
      repo: https://github.com/madgeek-arc/resource-catalogue-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-tomato-duck.sh
        container: qc.acc_gloppy-amaranth-zorse
  QC.Doc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-mauve-moose.sh
        container: qc.doc_snappy-chestnut-ragdoll
      github.com/madgeek-arc/resource-catalogue-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cerise-manatee.sh
        container: qc.doc_gamy-fuchsia-havanese
      github.com/madgeek-arc/resource-catalogue-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-lavender-devil.sh
        container: qc.doc_scanty-cream-rottweiler
  QC.Lic:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-persimmon-penguin.sh
        container: qc.lic_scummy-eggplant-saola
  QC.Sty:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-azure-dhole.sh
        container: qc.sty_stinky-black-terrier
      github.com/madgeek-arc/resource-catalogue-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-violet-frigatebird.sh
        container: qc.sty_hilly-yellow-walrus
  QC.Ver:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-charcoal-hornet.sh
        container: qc.ver_silly-amethyst-gopher
timeout: 5400
